import type { Tag, Option } from "@suwatte/daisuke"

export const MIRRORS = [
  "https://mangapark.com",
  "https://mangapark.net",
  "https://mangapark.org",
  "https://mangapark.me",
  "https://mangapark.io",
  "https://mangapark.to",
  "https://comicpark.org",
  "https://comicpark.to",
  "https://readpark.org",
  "https://readpark.net",
  "https://parkmanga.com",
  "https://parkmanga.net",
  "https://parkmanga.org",
  "https://mpark.to",
]

export const SORT: Option[] = [
  { title: "Rating Score", id: "field_score" },
  { title: "Most Follows", id: "field_follow" },
  { title: "Most Reviews", id: "field_review" },
  { title: "Most Comments", id: "field_comment" },
  { title: "Most Chapters", id: "field_chapter" },
  { title: "New Chapters", id: "field_update" },
  { title: "Recently Created", id: "field_create" },
  { title: "Name A-Z", id: "field_name" },
  { title: "Total Views", id: "views_d000" },
  { title: "Most Views 360 days", id: "views_d360" },
  { title: "Most Views 180 days", id: "views_d180" },
  { title: "Most Views 90 days", id: "views_d090" },
  { title: "Most Views 30 days", id: "views_d030" },
  { title: "Most Views 7 days", id: "views_d007" },
  { title: "Most Views 24 hours", id: "views_h024" },
  { title: "Most Views 12 hours", id: "views_h012" },
  { title: "Most Views 6 hours", id: "views_h006" },
]

export const LANGUAGE: Tag[] = [
  { title: "Chinese", id: "zh" },
  { title: "English", id: "en" },
  { title: "Japanese", id: "ja" },
  { title: "Korean", id: "ko" },
]

export const STATUS: Tag[] = [
  { title: "All", id: "" },
  { title: "Pending", id: "pending" },
  { title: "Ongoing", id: "ongoing" },
  { title: "Completed", id: "completed" },
  { title: "Hiatus", id: "hiatus" },
  { title: "Cancelled", id: "cancelled" },
]

export const CHAPTERS: Tag[] = [
  { title: "0", id: "0" },
  { title: "1+", id: "1" },
  { title: "10+", id: "10" },
  { title: "20+", id: "20" },
  { title: "30+", id: "30" },
  { title: "40+", id: "40" },
  { title: "50+", id: "50" },
  { title: "60+", id: "60" },
  { title: "70+", id: "70" },
  { title: "80+", id: "80" },
  { title: "90+", id: "90" },
  { title: "100+", id: "100" },
  { title: "200+", id: "200" },
  { title: "300+", id: "300" },
  { title: "299~200", id: "200-299" },
  { title: "199~100", id: "100-199" },
  { title: "99~90", id: "90-99" },
  { title: "89~80", id: "80-89" },
  { title: "79~70", id: "70-79" },
  { title: "69~60", id: "60-69" },
  { title: "59~50", id: "50-59" },
  { title: "49~40", id: "40-49" },
  { title: "39~30", id: "30-39" },
  { title: "29~20", id: "20-29" },
  { title: "19~10", id: "10-19" },
  { title: "9~1", id: "1-9" },
]

export const CONTENT_TYPE: Tag[] = [
  { id: "cartoon", title: "cartoon" },
  { id: "doujinshi", title: "doujinshi" },
  { id: "manga", title: "manga" },
  { id: "manhwa", title: "manhwa" },
  { id: "western", title: "western" },
  { id: "oneshot", title: "oneshot" },
  { id: "_4_koma", title: "4 koma" },
]

export const DEMOGRAPHICS: Tag[] = [
  { id: "shoujo", title: "shoujo" },
  { id: "shounen", title: "shounen" },
  { id: "josei", title: "josei" },
  { id: "seinen", title: "seinen" },
  { id: "yuri", title: "yuri" },
  { id: "yaoi", title: "yaoi" },
  { id: "futa", title: "futa" },
  { id: "bara", title: "bara" },
  { id: "kodomo", title: "kodomo" },
  { id: "old_people", title: "old people" },
  { id: "non_human", title: "non human" },
]
export const ADULT_GENRES: Tag[] = [
  { id: "gore", title: "gore", nsfw: true },
  { id: "bloody", title: "bloody", nsfw: true },
  { id: "violence", title: "violence", nsfw: true },
  { id: "ecchi", title: "ecchi", nsfw: true },
  { id: "adult", title: "adult", nsfw: true },
  { id: "mature", title: "mature", nsfw: true },
  { id: "smut", title: "smut", nsfw: true },
  { id: "hentai", title: "hentai", nsfw: true },
]

export const GENRES: Tag[] = [
  { id: "action", title: "action" },
  { id: "adaptation", title: "adaptation" },
  { id: "adventure", title: "adventure" },
  { id: "age_gap", title: "age gap" },
  { id: "aliens", title: "aliens" },
  { id: "animals", title: "animals" },
  { id: "anthology", title: "anthology" },
  { id: "blackmail", title: "blackmail" },
  { id: "brocon_siscon", title: "brocon siscon" },
  { id: "cars", title: "cars" },
  { id: "comedy", title: "comedy" },
  { id: "cooking", title: "cooking" },
  { id: "crime", title: "crime" },
  { id: "crossdressing", title: "crossdressing" },
  { id: "cultivation", title: "cultivation" },
  { id: "death_game", title: "death game" },
  { id: "degeneratemc", title: "degeneratemc" },
  { id: "delinquents", title: "delinquents" },
  { id: "dementia", title: "dementia" },
  { id: "demons", title: "demons" },
  { id: "drama", title: "drama" },
  { id: "fantasy", title: "fantasy" },
  { id: "fan_colored", title: "fan colored" },
  { id: "fetish", title: "fetish" },
  { id: "full_color", title: "full color" },
  { id: "game", title: "game" },
  { id: "gender_bender", title: "gender bender" },
  { id: "genderswap", title: "genderswap" },
  { id: "ghosts", title: "ghosts" },
  { id: "gyaru", title: "gyaru" },
  { id: "harem", title: "harem" },
  { id: "harlequin", title: "harlequin" },
  { id: "historical", title: "historical" },
  { id: "horror", title: "horror" },
  { id: "incest", title: "incest" },
  { id: "isekai", title: "isekai" },
  { id: "kids", title: "kids" },
  { id: "loli", title: "loli" },
  { id: "magic", title: "magic" },
  { id: "magical_girls", title: "magical girls" },
  { id: "martial_arts", title: "martial arts" },
  { id: "master_servant", title: "master servant" },
  { id: "mecha", title: "mecha" },
  { id: "medical", title: "medical" },
  { id: "milf", title: "milf" },
  { id: "military", title: "military" },
  { id: "monster_girls", title: "monster girls" },
  { id: "monsters", title: "monsters" },
  { id: "music", title: "music" },
  { id: "mystery", title: "mystery" },
  { id: "netorare", title: "netorare" },
  { id: "ninja", title: "ninja" },
  { id: "office_workers", title: "office workers" },
  { id: "omegaverse", title: "omegaverse" },
  { id: "parody", title: "parody" },
  { id: "philosophical", title: "philosophical" },
  { id: "police", title: "police" },
  { id: "post_apocalyptic", title: "post apocalyptic" },
  { id: "psychological", title: "psychological" },
  { id: "reincarnation", title: "reincarnation" },
  { id: "reverse_harem", title: "reverse harem" },
  { id: "romance", title: "romance" },
  { id: "samurai", title: "samurai" },
  { id: "school_life", title: "school life" },
  { id: "sci_fi", title: "sci fi" },
  { id: "shota", title: "shota" },
  { id: "shoujo_ai", title: "shoujo ai" },
  { id: "shounen_ai", title: "shounen ai" },
  { id: "showbiz", title: "showbiz" },
  { id: "slice_of_life", title: "slice of life" },
  { id: "sm_bdsm", title: "sm bdsm" },
  { id: "space", title: "space" },
  { id: "sports", title: "sports" },
  { id: "step_family", title: "step family" },
  { id: "super_power", title: "super power" },
  { id: "superhero", title: "superhero" },
  { id: "supernatural", title: "supernatural" },
  { id: "survival", title: "survival" },
  { id: "teacher_student", title: "teacher student" },
  { id: "thriller", title: "thriller" },
  { id: "time_travel", title: "time travel" },
  { id: "traditional_games", title: "traditional games" },
  { id: "tragedy", title: "tragedy" },
  { id: "vampires", title: "vampires" },
  { id: "video_games", title: "video games" },
  { id: "villainess", title: "villainess" },
  { id: "virtual_reality", title: "virtual reality" },
  { id: "wuxia", title: "wuxia" },
  { id: "xianxia", title: "xianxia" },
  { id: "xuanhuan", title: "xuanhuan" },
  { id: "zombies", title: "zombies" },
]

export const ALL_GENRES: Tag[] = [
  ...DEMOGRAPHICS,
  ...ADULT_GENRES,
  ...GENRES,
  ...CONTENT_TYPE,
]
