import { Option, Tag } from "@suwatte/daisuke"
export const CONTENT_TYPE: Tag[] = [
  { id: "cartoon", title: "cartoon" },
  { id: "doujinshi", title: "doujinshi" },
  { id: "manga", title: "manga" },
  { id: "manhwa", title: "manhwa" },
  { id: "western", title: "western" },
  { id: "oneshot", title: "oneshot" },
  { id: "_4_koma", title: "4 koma" },
]
export const DEMOGRAPHICS: Tag[] = [
  { id: "shoujo", title: "shoujo" },
  { id: "shounen", title: "shounen" },
  { id: "josei", title: "josei" },
  { id: "seinen", title: "seinen" },
  { id: "yuri", title: "yuri" },
  { id: "yaoi", title: "yaoi" },
  { id: "futa", title: "futa" },
  { id: "bara", title: "bara" },
  { id: "kodomo", title: "kodomo" },
  { id: "old_people", title: "old people" },
  { id: "non_human", title: "non human" },
]
export const ADULT_GENRES: Tag[] = [
  { id: "gore", title: "gore", nsfw: true },
  { id: "bloody", title: "bloody", nsfw: true },
  { id: "violence", title: "violence", nsfw: true },
  { id: "ecchi", title: "ecchi", nsfw: true },
  { id: "adult", title: "adult", nsfw: true },
  { id: "mature", title: "mature", nsfw: true },
  { id: "smut", title: "smut", nsfw: true },
  { id: "hentai", title: "hentai", nsfw: true },
]
export const GENRES: Tag[] = [
  { id: "_4_koma", title: "4-Koma", nsfw: false },
  { id: "action", title: "Action", nsfw: false },
  { id: "adaptation", title: "Adaptation", nsfw: false },
  { id: "adventure", title: "Adventure", nsfw: false },
  { id: "age_gap", title: "Age Gap", nsfw: false },
  { id: "aliens", title: "Aliens", nsfw: false },
  { id: "animals", title: "Animals", nsfw: false },
  { id: "anthology", title: "Anthology", nsfw: false },
  { id: "beasts", title: "Beasts", nsfw: false },
  { id: "bodyswap", title: "Bodyswap", nsfw: false },
  { id: "cars", title: "Cars", nsfw: false },
  {
    id: "cheating_infidelity",
    title: "Cheating/Infidelity",
    nsfw: false,
  },
  {
    id: "childhood_friends",
    title: "Childhood Friends",
    nsfw: false,
  },
  { id: "college_life", title: "College life ", nsfw: false },
  { id: "comedy", title: "Comedy", nsfw: false },
  {
    id: "contest_winning",
    title: "Contest winning",
    nsfw: false,
  },
  { id: "cooking", title: "Cooking", nsfw: false },
  { id: "crime", title: "Crime", nsfw: false },
  { id: "crossdressing", title: "Crossdressing", nsfw: false },
  { id: "delinquents", title: "Delinquents", nsfw: false },
  { id: "dementia", title: "Dementia", nsfw: false },
  { id: "demons", title: "Demons", nsfw: false },
  { id: "drama", title: "Drama", nsfw: false },
  { id: "dungeons", title: "Dungeons", nsfw: false },
  {
    id: "emperor_daughte",
    title: "Emperor's daughte",
    nsfw: false,
  },
  { id: "fantasy", title: "Fantasy", nsfw: false },
  { id: "fan_colored", title: "Fan-Colored", nsfw: false },
  { id: "fetish", title: "Fetish", nsfw: false },
  { id: "full_color", title: "Full Color", nsfw: false },
  { id: "game", title: "Game", nsfw: false },
  { id: "gender_bender", title: "Gender Bender", nsfw: false },
  { id: "genderswap", title: "Genderswap", nsfw: false },
  { id: "ghosts", title: "Ghosts", nsfw: false },
  { id: "gyaru", title: "Gyaru", nsfw: false },
  { id: "harem", title: "Harem", nsfw: false },
  { id: "harlequin", title: "Harlequin", nsfw: false },
  { id: "historical", title: "Historical", nsfw: false },
  { id: "horror", title: "Horror", nsfw: false },
  { id: "incest", title: "Incest", nsfw: false },
  { id: "isekai", title: "Isekai", nsfw: false },
  { id: "kids", title: "Kids", nsfw: false },
  { id: "loli", title: "Loli", nsfw: false },
  { id: "magic", title: "Magic", nsfw: false },
  { id: "magical_girls", title: "Magical Girls", nsfw: false },
  { id: "martial_arts", title: "Martial Arts", nsfw: false },
  { id: "mecha", title: "Mecha", nsfw: false },
  { id: "medical", title: "Medical", nsfw: false },
  { id: "military", title: "Military", nsfw: false },
  { id: "monster_girls", title: "Monster Girls", nsfw: false },
  { id: "monsters", title: "Monsters", nsfw: false },
  { id: "music", title: "Music", nsfw: false },
  { id: "mystery", title: "Mystery", nsfw: false },
  { id: "netorare", title: "Netorare/NTR", nsfw: false },
  { id: "ninja", title: "Ninja", nsfw: false },
  { id: "office_workers", title: "Office Workers", nsfw: false },
  { id: "omegaverse", title: "Omegaverse", nsfw: false },
  { id: "oneshot", title: "Oneshot", nsfw: false },
  { id: "parody", title: "parody", nsfw: false },
  { id: "philosophical", title: "Philosophical", nsfw: false },
  { id: "police", title: "Police", nsfw: false },
  {
    id: "post_apocalyptic",
    title: "Post-Apocalyptic",
    nsfw: false,
  },
  { id: "psychological", title: "Psychological", nsfw: false },
  { id: "regression", title: "Regression", nsfw: false },
  { id: "reincarnation", title: "Reincarnation", nsfw: false },
  { id: "reverse_harem", title: "Reverse Harem", nsfw: false },
  { id: "revenge", title: "Revenge", nsfw: false },
  { id: "reverse_isekai", title: "Reverse Isekai ", nsfw: false },
  { id: "romance", title: "Romance", nsfw: false },
  { id: "royal_family", title: "Royal family", nsfw: false },
  { id: "royalty", title: "Royalty", nsfw: false },
  { id: "samurai", title: "Samurai", nsfw: false },
  { id: "school_life", title: "School Life", nsfw: false },
  { id: "sci_fi", title: "Sci-Fi", nsfw: false },
  { id: "shota", title: "Shota", nsfw: false },
  { id: "shoujo_ai", title: "Shoujo ai", nsfw: false },
  { id: "shounen_ai", title: "Shounen ai", nsfw: false },
  { id: "showbiz", title: "Showbiz", nsfw: false },
  { id: "slice_of_life", title: "Slice of Life", nsfw: false },
  { id: "sm_bdsm", title: "SM/BDSM/SUB-DOM", nsfw: false },
  { id: "space", title: "Space", nsfw: false },
  { id: "sports", title: "Sports", nsfw: false },
  { id: "super_power", title: "Super Power", nsfw: false },
  { id: "superhero", title: "Superhero", nsfw: false },
  { id: "supernatural", title: "Supernatural", nsfw: false },
  { id: "survival", title: "Survival", nsfw: false },
  { id: "thriller", title: "Thriller", nsfw: false },
  { id: "time_travel", title: "Time Travel", nsfw: false },
  { id: "tower_climbing", title: "Tower Climbing", nsfw: false },
  {
    id: "traditional_games",
    title: "Traditional Games",
    nsfw: false,
  },
  { id: "tragedy", title: "Tragedy", nsfw: false },
  { id: "transmigration", title: "Transmigration", nsfw: false },
  { id: "vampires", title: "Vampires", nsfw: false },
  { id: "villainess", title: "Villainess", nsfw: false },
  { id: "video_games", title: "Video Games", nsfw: false },
  {
    id: "virtual_reality",
    title: "Virtual Reality",
    nsfw: false,
  },
  { id: "wuxia", title: "Wuxia", nsfw: false },
  { id: "xianxia", title: "Xianxia", nsfw: false },
  { id: "xuanhuan", title: "Xuanhuan", nsfw: false },
  { id: "yakuzas", title: "Yakuzas", nsfw: false },
  { id: "zombies", title: "Zombies", nsfw: false },
]

export const ALL_GENRES: Tag[] = [
  ...DEMOGRAPHICS,
  ...ADULT_GENRES,
  ...GENRES,
  ...CONTENT_TYPE,
]


export const STATUS_TAGS: Tag[] = [
  { id: "pending", title: "Pending", nsfw: false },
  { id: "ongoing", title: "Ongoing", nsfw: false },
  { id: "completed", title: "Completed", nsfw: false },
  { id: "hiatus", title: "Hiatus", nsfw: false },
  { id: "cancelled", title: "Cancelled", nsfw: false },
]

export const ORIGIN_TAGS: Tag[] = [
  { id: "zh", title: "Chinese", nsfw: false },
  { id: "en", title: "English", nsfw: false },
  { id: "ja", title: "Japanese", nsfw: false },
  { id: "ko", title: "Korean", nsfw: false },
  { id: "af", title: "Afrikaans", nsfw: false },
  { id: "sq", title: "Albanian", nsfw: false },
  { id: "am", title: "Amharic", nsfw: false },
  { id: "ar", title: "Arabic", nsfw: false },
  { id: "hy", title: "Armenian", nsfw: false },
  { id: "az", title: "Azerbaijani", nsfw: false },
  { id: "be", title: "Belarusian", nsfw: false },
  { id: "bn", title: "Bengali", nsfw: false },
  { id: "bs", title: "Bosnian", nsfw: false },
  { id: "bg", title: "Bulgarian", nsfw: false },
  { id: "my", title: "Burmese", nsfw: false },
  { id: "km", title: "Cambodian", nsfw: false },
  { id: "ca", title: "Catalan", nsfw: false },
  { id: "ceb", title: "Cebuano", nsfw: false },
  { id: "zh_hk", title: "Chinese (Cantonese)", nsfw: false },
  { id: "zh_tw", title: "Chinese (Traditional)", nsfw: false },
  { id: "hr", title: "Croatian", nsfw: false },
  { id: "cs", title: "Czech", nsfw: false },
  { id: "da", title: "Danish", nsfw: false },
  { id: "nl", title: "Dutch", nsfw: false },
  { id: "en_us", title: "English (United States)", nsfw: false },
  { id: "eo", title: "Esperanto", nsfw: false },
  { id: "et", title: "Estonian", nsfw: false },
  { id: "fo", title: "Faroese", nsfw: false },
  { id: "fil", title: "Filipino", nsfw: false },
  { id: "fi", title: "Finnish", nsfw: false },
  { id: "fr", title: "French", nsfw: false },
  { id: "ka", title: "Georgian", nsfw: false },
  { id: "de", title: "German", nsfw: false },
  { id: "el", title: "Greek", nsfw: false },
  { id: "gn", title: "Guarani", nsfw: false },
  { id: "gu", title: "Gujarati", nsfw: false },
  { id: "ht", title: "Haitian Creole", nsfw: false },
  { id: "ha", title: "Hausa", nsfw: false },
  { id: "he", title: "Hebrew", nsfw: false },
  { id: "hi", title: "Hindi", nsfw: false },
  { id: "hu", title: "Hungarian", nsfw: false },
  { id: "is", title: "Icelandic", nsfw: false },
  { id: "ig", title: "Igbo", nsfw: false },
  { id: "id", title: "Indonesian", nsfw: false },
  { id: "ga", title: "Irish", nsfw: false },
  { id: "it", title: "Italian", nsfw: false },
  { id: "jv", title: "Javanese", nsfw: false },
  { id: "kn", title: "Kannada", nsfw: false },
  { id: "kk", title: "Kazakh", nsfw: false },
  { id: "ku", title: "Kurdish", nsfw: false },
  { id: "ky", title: "Kyrgyz", nsfw: false },
  { id: "lo", title: "Laothian", nsfw: false },
  { id: "lv", title: "Latvian", nsfw: false },
  { id: "lt", title: "Lithuanian", nsfw: false },
  { id: "lb", title: "Luxembourgish", nsfw: false },
  { id: "mk", title: "Macedonian", nsfw: false },
  { id: "mg", title: "Malagasy", nsfw: false },
  { id: "ms", title: "Malay", nsfw: false },
  { id: "ml", title: "Malayalam", nsfw: false },
  { id: "mt", title: "Maltese", nsfw: false },
  { id: "mi", title: "Maori", nsfw: false },
  { id: "mr", title: "Marathi", nsfw: false },
  { id: "mo", title: "Moldavian", nsfw: false },
  { id: "mn", title: "Mongolian", nsfw: false },
  { id: "ne", title: "Nepali", nsfw: false },
  { id: "no", title: "Norwegian", nsfw: false },
  { id: "ny", title: "Nyanja", nsfw: false },
  { id: "ps", title: "Pashto", nsfw: false },
  { id: "fa", title: "Persian", nsfw: false },
  { id: "pl", title: "Polish", nsfw: false },
  { id: "pt", title: "Portuguese", nsfw: false },
  { id: "pt_br", title: "Portuguese (Brazil)", nsfw: false },
  { id: "ro", title: "Romanian", nsfw: false },
  { id: "rm", title: "Romansh", nsfw: false },
  { id: "ru", title: "Russian", nsfw: false },
  { id: "sm", title: "Samoan", nsfw: false },
  { id: "sr", title: "Serbian", nsfw: false },
  { id: "sh", title: "Serbo-Croatian", nsfw: false },
  { id: "st", title: "Sesotho", nsfw: false },
  { id: "sn", title: "Shona", nsfw: false },
  { id: "sd", title: "Sindhi", nsfw: false },
  { id: "si", title: "Sinhalese", nsfw: false },
  { id: "sk", title: "Slovak", nsfw: false },
  { id: "sl", title: "Slovenian", nsfw: false },
  { id: "so", title: "Somali", nsfw: false },
  { id: "es", title: "Spanish", nsfw: false },
  {
    id: "es_419",
    title: "Spanish (Latin America)",
    nsfw: false,
  },
  { id: "sw", title: "Swahili", nsfw: false },
  { id: "sv", title: "Swedish", nsfw: false },
  { id: "tg", title: "Tajik", nsfw: false },
  { id: "ta", title: "Tamil", nsfw: false },
  { id: "th", title: "Thai", nsfw: false },
  { id: "ti", title: "Tigrinya", nsfw: false },
  { id: "to", title: "Tonga", nsfw: false },
  { id: "tr", title: "Turkish", nsfw: false },
  { id: "tk", title: "Turkmen", nsfw: false },
  { id: "uk", title: "Ukrainian", nsfw: false },
  { id: "ur", title: "Urdu", nsfw: false },
  { id: "uz", title: "Uzbek", nsfw: false },
  { id: "vi", title: "Vietnamese", nsfw: false },
  { id: "yo", title: "Yoruba", nsfw: false },
  { id: "zu", title: "Zulu", nsfw: false },
  { id: "_t", title: "Other", nsfw: false },
]

export const LANG_TAGS: Tag[] = [
  { id: "en", title: "English", nsfw: false },
  { id: "ar", title: "Arabic", nsfw: false },
  { id: "bg", title: "Bulgarian", nsfw: false },
  { id: "zh", title: "Chinese", nsfw: false },
  { id: "cs", title: "Czech", nsfw: false },
  { id: "da", title: "Danish", nsfw: false },
  { id: "nl", title: "Dutch", nsfw: false },
  { id: "fil", title: "Filipino", nsfw: false },
  { id: "fi", title: "Finnish", nsfw: false },
  { id: "fr", title: "French", nsfw: false },
  { id: "de", title: "German", nsfw: false },
  { id: "el", title: "Greek", nsfw: false },
  { id: "he", title: "Hebrew", nsfw: false },
  { id: "hi", title: "Hindi", nsfw: false },
  { id: "hu", title: "Hungarian", nsfw: false },
  { id: "id", title: "Indonesian", nsfw: false },
  { id: "it", title: "Italian", nsfw: false },
  { id: "ja", title: "Japanese", nsfw: false },
  { id: "ko", title: "Korean", nsfw: false },
  { id: "ms", title: "Malay", nsfw: false },
  { id: "pl", title: "Polish", nsfw: false },
  { id: "pt", title: "Portuguese", nsfw: false },
  { id: "pt_br", title: "Portuguese (Brazil)", nsfw: false },
  { id: "ro", title: "Romanian", nsfw: false },
  { id: "ru", title: "Russian", nsfw: false },
  { id: "es", title: "Spanish", nsfw: false },
  { id: "es_419", title: "Spanish (Latin America)", nsfw: false },
  { id: "sv", title: "Swedish", nsfw: false },
  { id: "th", title: "Thai", nsfw: false },
  { id: "tr", title: "Turkish", nsfw: false },
  { id: "uk", title: "Ukrainian", nsfw: false },
  { id: "vi", title: "Vietnamese", nsfw: false },
  { id: "af", title: "Afrikaans", nsfw: false },
  { id: "sq", title: "Albanian", nsfw: false },
  { id: "am", title: "Amharic", nsfw: false },
  { id: "hy", title: "Armenian", nsfw: false },
  { id: "az", title: "Azerbaijani", nsfw: false },
  { id: "be", title: "Belarusian", nsfw: false },
  { id: "bn", title: "Bengali", nsfw: false },
  { id: "bs", title: "Bosnian", nsfw: false },
  { id: "my", title: "Burmese", nsfw: false },
  { id: "km", title: "Cambodian", nsfw: false },
  { id: "ca", title: "Catalan", nsfw: false },
  { id: "ceb", title: "Cebuano", nsfw: false },
  { id: "zh_hk", title: "Chinese (Cantonese)", nsfw: false },
  { id: "zh_tw", title: "Chinese (Traditional)", nsfw: false },
  { id: "hr", title: "Croatian", nsfw: false },
  { id: "en_us", title: "English (United States)", nsfw: false },
  { id: "eo", title: "Esperanto", nsfw: false },
  { id: "et", title: "Estonian", nsfw: false },
  { id: "fo", title: "Faroese", nsfw: false },
  { id: "ka", title: "Georgian", nsfw: false },
  { id: "gn", title: "Guarani", nsfw: false },
  { id: "gu", title: "Gujarati", nsfw: false },
  { id: "ht", title: "Haitian Creole", nsfw: false },
  { id: "ha", title: "Hausa", nsfw: false },
  { id: "is", title: "Icelandic", nsfw: false },
  { id: "ig", title: "Igbo", nsfw: false },
  { id: "ga", title: "Irish", nsfw: false },
  { id: "jv", title: "Javanese", nsfw: false },
  { id: "kn", title: "Kannada", nsfw: false },
  { id: "kk", title: "Kazakh", nsfw: false },
  { id: "ku", title: "Kurdish", nsfw: false },
  { id: "ky", title: "Kyrgyz", nsfw: false },
  { id: "lo", title: "Laothian", nsfw: false },
  { id: "lv", title: "Latvian", nsfw: false },
  { id: "lt", title: "Lithuanian", nsfw: false },
  { id: "lb", title: "Luxembourgish", nsfw: false },
  { id: "mk", title: "Macedonian", nsfw: false },
  { id: "mg", title: "Malagasy", nsfw: false },
  { id: "ml", title: "Malayalam", nsfw: false },
  { id: "mt", title: "Maltese", nsfw: false },
  { id: "mi", title: "Maori", nsfw: false },
  { id: "mr", title: "Marathi", nsfw: false },
  { id: "mo", title: "Moldavian", nsfw: false },
  { id: "mn", title: "Mongolian", nsfw: false },
  { id: "ne", title: "Nepali", nsfw: false },
  { id: "no", title: "Norwegian", nsfw: false },
  { id: "ny", title: "Nyanja", nsfw: false },
  { id: "ps", title: "Pashto", nsfw: false },
  { id: "fa", title: "Persian", nsfw: false },
  { id: "rm", title: "Romansh", nsfw: false },
  { id: "sm", title: "Samoan", nsfw: false },
  { id: "sr", title: "Serbian", nsfw: false },
  { id: "sh", title: "Serbo-Croatian", nsfw: false },
  { id: "st", title: "Sesotho", nsfw: false },
  { id: "sn", title: "Shona", nsfw: false },
  { id: "sd", title: "Sindhi", nsfw: false },
  { id: "si", title: "Sinhalese", nsfw: false },
  { id: "sk", title: "Slovak", nsfw: false },
  { id: "sl", title: "Slovenian", nsfw: false },
  { id: "so", title: "Somali", nsfw: false },
  { id: "sw", title: "Swahili", nsfw: false },
  { id: "tg", title: "Tajik", nsfw: false },
  { id: "ta", title: "Tamil", nsfw: false },
  { id: "ti", title: "Tigrinya", nsfw: false },
  { id: "to", title: "Tonga", nsfw: false },
  { id: "tk", title: "Turkmen", nsfw: false },
  { id: "ur", title: "Urdu", nsfw: false },
  { id: "uz", title: "Uzbek", nsfw: false },
  { id: "yo", title: "Yoruba", nsfw: false },
  { id: "zu", title: "Zulu", nsfw: false },
  { id: "_t", title: "Other", nsfw: false },
]

export const CHAPTERS: Tag[] = [
  { id: "", title: "All" },
  { id: "1~9", title: "1-9" },
  { id: "10~29", title: "10-29" },
  { id: "30~99", title: "30-99" },
  { id: "100~199", title: "100-199" },
  { id: "200", title: "+200" },
  { id: "100", title: "+100" },
  { id: "50", title: "+50" },
  { id: "10", title: "+10" },
  { id: "1", title: "+1" },
]


export const sort: Option[] = [
  {id: "field_score", title:"Rating Score"},
  {id: "field_score", title:"Rating Score"},
  {id: "field_follow", title:"Most Follows"},
  {id: "field_review", title:"Most Reviews"},
  {id: "field_comment", title:"Most Comments"},
  {id: "field_chapter", title:"Most Chapters"},
  {id: "field_upload", title:"Latest Upload"},
  {id: "field_public", title:"Recently Created"},
  {id: "field_name", title:"Name A-Z"},
  {id: "views_h001", title:"60 minutes"},
  {id: "views_h006", title:"6 hours"},
  {id: "views_h012", title:"12 hours"},
  {id: "views_h024", title:"24 hours"},
  {id: "views_d007", title:"7 days"},
  {id: "views_d030", title:"30 days"},
  {id: "views_d090", title:"90 days"},
  {id: "views_d180", title:"180 days"},
  {id: "views_d360", title:"360 days"},
  {id: "views_d000", title:"Total"},
  {id: "status_wish", title:"Plan to read"},
  {id: "status_doing", title:"Reading"},
  {id: "status_completed", title:"Completed"},
  {id: "status_on_hold", title:"On hold"},
  {id: "status_dropped", title:"Dropped"},
  {id: "status_repeat", title:"Re-reading"},
  {id: "emotion_upvote", title:"Awesome"},
  {id: "emotion_funny", title:"Funny"},
  {id: "emotion_love", title:"Love"},
  {id: "emotion_surprised", title:"Scared"},
  {id: "emotion_angry", title:"Angry"},
  {id: "emotion_sad", title:"Sad"},
]
