export declare const CurrentViewerQuery = "\nquery CurrentUser {\n    Viewer {\n    id\n    name\n    about\n    avatar {\n      large\n    }\n    bannerImage\n    options {\n      titleLanguage,\n      displayAdultContent\n    }\n    mediaListOptions {\n      scoreFormat\n      rowOrder\n      mangaList {\n        customLists\n        sectionOrder\n        }\n      }\n    }\n}";
export declare const CurrentViewerScoreFormatQuery = "\nquery ScoreFormat {\n      Viewer {\n        mediaListOptions {\n          scoreFormat\n        }\n      }\n    }\n";
export declare const MediaListEntryQuery = "\nquery ($id: Int) {\n    Media(id: $id) {\n    id\n    title {\n        userPreferred\n    }\n    coverImage {\n        large\n    }\n    chapters\n    volumes\n    mediaListEntry {\n        status\n        score(format: POINT_100)\n        progress\n        progressVolumes\n        repeat\n        private\n        notes\n        hiddenFromStatusLists\n        customLists(asArray: true)\n        startedAt {\n            year\n            month\n            day\n        }\n        completedAt {\n            year\n            month\n            day\n            }\n        }\n    }\n}";
export declare const SimpleSearchQuery = "\nquery SimpleSearch ($search: String) {\n      Page(perPage: 30) {\n        media(search: $search, type: MANGA) {\n          id\n          title {\n            userPreferred\n          }\n          coverImage {\n            large\n          }\n        }\n      }\n    }";
export declare const HomePageQuery: string;
export declare const HomePageViewMoreQuery: (key: string) => string;
export declare const MediaListCollectionQuery: string;
export declare const FullMediaQuery: string;
export declare const FullSearchQuery: string;
export declare const GenresQuery = "\n    query {\n      genres: GenreCollection\n      tags: MediaTagCollection {\n        name\n        description\n        category\n        isAdult\n      }\n    }";
