import { Tag } from "@suwatte/daisuke"

export const GENRES: Tag[] = [
  { id: "adult", title: "Adult" },
  { id: "drama", title: "Drama" },
  { id: "harem", title: "Harem" },
  { id: "seinen", title: "Seinen" },
  { id: "school-life", title: "School Life" },
  { id: "mature", title: "Mature" },
  { id: "psychological", title: "Psychological" },
  { id: "romance", title: "Romance" },
  { id: "tragedy", title: "Tragedy" },
  { id: "ecchi", title: "Ecchi" },
  { id: "sci-fi", title: "Sci-fi" },
  { id: "yaoi", title: "Yaoi" },
  { id: "action", title: "Action" },
  { id: "martial-arts", title: "Martial Arts" },
  { id: "smut", title: "Smut" },
  { id: "sports", title: "Sports" },
  { id: "comedy", title: "Comedy" },
  { id: "yuri", title: "Yuri" },
  { id: "slice-of-life", title: "Slice of Life" },
  { id: "fantasy", title: "Fantasy" },
  { id: "horror", title: "Horror" },
  { id: "supernatural", title: "Supernatural" },
  { id: "hentai", title: "Hentai" },
  { id: "isekai", title: "Isekai" },
  { id: "shoujo", title: "Shoujo" },
  { id: "adventure", title: "Adventure" },
  { id: "shounen", title: "Shounen" },
  { id: "mecha", title: "Mecha" },
  { id: "mystery", title: "Mystery" },
  { id: "thriller", title: "Thriller" },
  { id: "historical", title: "Historical" },
  { id: "josei", title: "Josei" },
  { id: "gender-bender", title: "Gender Bender" },
  { id: "webtoons", title: "Webtoons" },
  { id: "rpg", title: "RPG" },
  { id: "gl", title: "GL" },
  { id: "bl", title: "BL" },
  { id: "raw", title: "Raw" },
  { id: "reincarnation", title: "Reincarnation" },
  { id: "zombie", title: "Zombie" },
  { id: "magic", title: "Magic" },
  { id: "comics", title: "Comics" },
  { id: "webtoon", title: "Webtoon" },
  { id: "cooking", title: "Cooking" },
  { id: "ntr", title: "NTR" },
  { id: "doujinshi", title: "Doujinshi" },
  { id: "game", title: "Game" },
  { id: "vanilla", title: "Vanilla" },
  { id: "demons", title: "Demons" },
  { id: "family", title: "Family" },
  { id: "manga", title: "Manga" },
  { id: "super-power", title: "Super Power" },
]
