import { type Tag } from "@suwatte/daisuke"

export const GENRES: Tag[] = [
  { id: "6", title: "Action" },
  { id: "87264", title: "Adult" },
  { id: "7", title: "Adventure" },
  { id: "8", title: "Boys Love" },
  { id: "9", title: "Comedy" },
  { id: "10", title: "Crime" },
  { id: "11", title: "Drama" },
  { id: "87265", title: "Ecchi" },
  { id: "12", title: "Fantasy" },
  { id: "13", title: "Girls Love" },
  { id: "87266", title: "Hentai" },
  { id: "14", title: "Historical" },
  { id: "15", title: "Horror" },
  { id: "16", title: "Isekai" },
  { id: "17", title: "Magical Girls" },
  { id: "87267", title: "Mature" },
  { id: "18", title: "Mecha" },
  { id: "19", title: "Medical" },
  { id: "20", title: "Mystery" },
  { id: "21", title: "Philosophical" },
  { id: "22", title: "Psychological" },
  { id: "23", title: "Romance" },
  { id: "24", title: "Sci-Fi" },
  { id: "25", title: "Slice of Life" },
  { id: "87268", title: "Smut" },
  { id: "26", title: "Sports" },
  { id: "27", title: "Superhero" },
  { id: "28", title: "Thriller" },
  { id: "29", title: "Tragedy" },
  { id: "30", title: "Wuxia" },
  { id: "31", title: "Aliens" },
  { id: "32", title: "Animals" },
  { id: "33", title: "Cooking" },
  { id: "34", title: "Cross Dressing" },
  { id: "35", title: "Delinquents" },
  { id: "36", title: "Demons" },
  { id: "37", title: "Genderswap" },
  { id: "38", title: "Ghosts" },
  { id: "39", title: "Gyaru" },
  { id: "40", title: "Harem" },
  { id: "41", title: "Incest" },
  { id: "42", title: "Loli" },
  { id: "43", title: "Mafia" },
  { id: "44", title: "Magic" },
  { id: "45", title: "Martial Arts" },
  { id: "46", title: "Military" },
  { id: "47", title: "Monster Girls" },
  { id: "48", title: "Monsters" },
  { id: "49", title: "Music" },
  { id: "50", title: "Ninja" },
  { id: "51", title: "Office Workers" },
  { id: "52", title: "Police" },
  { id: "53", title: "Post-Apocalyptic" },
  { id: "54", title: "Reincarnation" },
  { id: "55", title: "Reverse Harem" },
  { id: "56", title: "Samurai" },
  { id: "57", title: "School Life" },
  { id: "58", title: "Shota" },
  { id: "59", title: "Supernatural" },
  { id: "60", title: "Survival" },
  { id: "61", title: "Time Travel" },
  { id: "62", title: "Traditional Games" },
  { id: "63", title: "Vampires" },
  { id: "64", title: "Video Games" },
  { id: "65", title: "Villainess" },
  { id: "66", title: "Virtual Reality" },
  { id: "67", title: "Zombies" },
]

export const SORTS = [
  { id: "views_30d", title: "Popular" },
  { id: "chapter_updated_at", title: "Latest Updated" },
  { id: "created_at", title: "Created" },
  { id: "title", title: "Title" },
  { id: "views_total", title: "Total Views" },
  { id: "follows_total", title: "Most Follows" },
]

export const STATUSES: Tag[] = [
  { id: "releasing", title: "Releasing" },
  { id: "finished", title: "Finished" },
  { id: "on_hiatus", title: "On Hiatus" },
  { id: "discontinued", title: "Discontinued" },
  { id: "not_yet_released", title: "Not Yet Released" },
]

export const TYPES: Tag[] = [
  { id: "manga", title: "Manga" },
  { id: "manhwa", title: "Manhwa" },
  { id: "manhua", title: "Manhua" },
  { id: "other", title: "Other" },
]

export const DEMOGRAPHICS: Tag[] = [
  { id: "1", title: "Shoujo" },
  { id: "2", title: "Shounen" },
  { id: "3", title: "Josei" },
  { id: "4", title: "Seinen" },
]
