"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Target = void 0;
const daisuke_1 = require("@suwatte/daisuke");
// Note: Chapter API requires hash token generated by site's obfuscated VM bundle.
// The Tachiyomi extension uses a hidden WebView to sign requests dynamically.
// We throw CloudflareError to trigger WebView resolution, which shares cookies.
let pendingResolutionURL;
const constants_1 = require("./constants");
// Firefox-style headers - Cloudflare is more lenient with Firefox fingerprints
const USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:140.0) Gecko/20100101 Firefox/140.0";
class Target {
    baseUrl = "https://comix.to";
    apiUrl = "https://comix.to/api/v1";
    info = {
        id: "kusa.comix",
        name: "Comix",
        thumbnail: "comix.png",
        version: 1.05,
        website: "https://comix.to",
        supportedLanguages: ["EN_US"],
        rating: daisuke_1.CatalogRating.MIXED,
        minSupportedAppVersion: "5.0",
    };
    get config() {
        return {
            // Suwatte will open this URL in WebView for Cloudflare challenge resolution
            // After solving, cookies (including cf_clearance) are shared with NetworkClient
            cloudflareResolutionURL: pendingResolutionURL ?? `${this.baseUrl}/`,
        };
    }
    client = new daisuke_1.NetworkClientBuilder()
        .addRequestInterceptor(async (req) => {
        return {
            ...req,
            headers: {
                ...req.headers,
                "user-agent": USER_AGENT,
                accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
                "accept-language": "en-US,en;q=0.9",
                "accept-encoding": "gzip, deflate, br, zstd",
                "sec-fetch-dest": "empty",
                "sec-fetch-mode": "cors",
                "sec-fetch-site": "same-origin",
                "sec-gpc": "1",
            },
        };
    })
        .build();
    // ImageRequestHandler — add Referer and UA for images
    async willRequestImage(url) {
        return {
            url,
            headers: {
                referer: `${this.baseUrl}/`,
                "user-agent": USER_AGENT,
                accept: "image/avif,image/webp,image/apng,image/png,image/jpeg,*/*;q=0.8",
                "accept-language": "en-US,en;q=0.9",
                "accept-encoding": "gzip, deflate, br, zstd",
                "sec-fetch-dest": "image",
                "sec-fetch-mode": "no-cors",
                "sec-fetch-site": "same-site",
            },
        };
    }
    async getSectionsForPage(page) {
        if (page.id !== "home")
            throw new Error("Page not found");
        return [
            { id: "popular", title: "Most Popular", style: daisuke_1.SectionStyle.GALLERY },
            { id: "latest", title: "Latest Updated", style: daisuke_1.SectionStyle.GALLERY },
            { id: "new", title: "New Releases", style: daisuke_1.SectionStyle.PADDED_LIST },
        ];
    }
    async resolvePageSection(link, sectionID) {
        if (link.id !== "home")
            throw new Error(`Unknown page: ${link.id}`);
        const orderMap = {
            popular: "views_30d",
            latest: "chapter_updated_at",
            new: "created_at",
        };
        const order = orderMap[sectionID];
        if (!order)
            throw new Error(`Unknown section: ${sectionID}`);
        const url = `${this.apiUrl}/manga?order[${order}]=desc&limit=28&page=1`;
        const response = await this.client.get(url);
        const data = JSON.parse(response.data);
        return {
            items: data.result.items.map(mangaToHighlight),
        };
    }
    async getDirectory(request) {
        let queryString = "";
        const { genres, status, type, demographic } = request.filters ?? {};
        if (genres) {
            const { included, excluded } = genres;
            if (included) {
                queryString += "&genres_mode=and";
                queryString += "&" + included.map((v) => `genres_in[]=${v}`).join("&");
            }
            if (excluded) {
                queryString += "&genres_mode=and";
                queryString += "&" + excluded.map((v) => `genres_ex[]=${v}`).join("&");
            }
        }
        if (status)
            queryString +=
                "&" + status.map((v) => `statuses[]=${v}`).join("&");
        if (type)
            queryString +=
                "&" + type.map((v) => `types[]=${v}`).join("&");
        if (demographic)
            queryString +=
                "&" +
                    demographic.map((v) => `demographics[]=${v}`).join("&");
        if (request.query) {
            queryString += `&keyword=${encodeURIComponent(request.query)}`;
            queryString += "&order[relevance]=desc";
        }
        else {
            const sortId = request.sort?.id ?? "score";
            const sortDir = request.sort?.ascending ? "asc" : "desc";
            queryString += `&order[${sortId}]=${sortDir}`;
        }
        queryString += `&limit=28&page=${request.page}`;
        const url = `${this.apiUrl}/manga?${queryString.replace(/^&/, "")}`;
        const response = await this.client.get(url);
        const data = JSON.parse(response.data);
        return {
            results: data.result.items.map(mangaToHighlight),
            isLastPage: data.result.meta
                ? data.result.meta.page >= data.result.meta.lastPage
                : data.result.pagination
                    ? data.result.pagination.current_page >=
                        data.result.pagination.last_page
                    : true,
        };
    }
    async getContent(contentId) {
        const hid = contentId.split("-")[0];
        const url = `${this.apiUrl}/manga/${hid}?includes[]=genre&includes[]=author&includes[]=artist&includes[]=theme&includes[]=demographic`;
        const response = await this.client.get(url);
        const data = JSON.parse(response.data);
        const manga = data.result;
        const status = convertStatus(manga.status);
        const chapters = await this.getChapters(hid);
        const properties = [];
        const genreTerms = [
            ...(manga.genre ?? []),
            ...(manga.demographic ?? []),
        ];
        if (genreTerms.length > 0)
            properties.push({
                id: "genres",
                title: "Genres",
                tags: genreTerms.map((t) => ({
                    id: t.slug,
                    title: t.title,
                    adultContent: false,
                })),
            });
        const creatorTerms = [...(manga.author ?? []), ...(manga.artist ?? [])];
        if (creatorTerms.length > 0)
            properties.push({
                id: "creators",
                title: "Credits",
                tags: creatorTerms.map((t) => ({
                    id: t.slug,
                    title: t.title,
                    noninteractive: true,
                    adultContent: false,
                })),
            });
        return {
            title: manga.title,
            cover: manga.poster?.large ?? "",
            summary: manga.synopsis ?? undefined,
            isNSFW: manga.content_rating === "erotica" ||
                manga.content_rating === "pornographic",
            status,
            chapters,
            properties,
            webUrl: `${this.baseUrl}/title/${contentId}`,
            recommendedPanelMode: daisuke_1.ReadingMode.WEBTOON,
        };
    }
    async getChapters(contentId) {
        const raw = [];
        let page = 1;
        let hasMore = true;
        while (hasMore) {
            // Chapter list API requires hash token - fetch from HTML instead
            // This is a fallback that should work after Cloudflare resolution
            const url = `${this.baseUrl}/title/${contentId}`;
            try {
                const response = await this.client.get(url);
                const html = response.data;
                const initialDataMatch = html.match(/<script type="application\/json" id="initial-data">(\{[\s\S]*?\})<\/script>/);
                if (initialDataMatch) {
                    const initialData = JSON.parse(initialDataMatch[1]);
                    // Extract chapters from manga detail if available
                    const queries = initialData.queries;
                    if (queries) {
                        for (const key of Object.keys(queries)) {
                            const data = queries[key];
                            if (data?.chapters) {
                                data.chapters.forEach((ch) => {
                                    raw.push(chapterToChapter(ch, raw.length));
                                });
                                hasMore = false;
                                break;
                            }
                        }
                    }
                }
                if (!hasMore)
                    break;
            }
            catch (e) {
                // Fall through to error
            }
            hasMore = false;
        }
        return raw.length > 0 ? raw.map((ch, i) => ({ ...ch, index: i })) : [];
    }
    async getChapterData(contentId, chapterId) {
        // Chapter API requires hash token generated by site's obfuscated VM bundle.
        // We read chapter data from HTML page instead.
        const chapterIdNum = chapterId.split("-")[0];
        const url = `${this.baseUrl}/title/${contentId}/${chapterIdNum}-chapter-${chapterIdNum}`;
        // Set resolution URL before attempting request
        pendingResolutionURL = url;
        const response = await this.client.get(url);
        const html = response.data;
        // Extract initial-data JSON from script tag
        const initialDataMatch = html.match(/<script type="application\/json" id="initial-data">(\{[\s\S]*?\})<\/script>/);
        if (!initialDataMatch) {
            // Throw CloudflareError to trigger WebView resolution with this chapter URL
            // The error is detected by name, and Suwatte will use config.cloudflareResolutionURL
            const error = new Error("Cloudflare");
            error.name = "CloudflareError";
            throw error;
        }
        try {
            const initialData = JSON.parse(initialDataMatch[1]);
            // Chapter pages are embedded in the queries object under chapter detail
            const queries = initialData.queries;
            if (!queries) {
                throw new Error("No queries data found");
            }
            // Find the chapter data in queries (keys are JSON arrays)
            for (const key of Object.keys(queries)) {
                const data = queries[key];
                if (data?.pages) {
                    return {
                        pages: data.pages.map((p) => ({ url: p.url })),
                    };
                }
            }
            throw new Error("No chapter pages found in initial data");
        }
        catch (e) {
            throw new Error(`Failed to parse chapter data: ${e}`);
        }
    }
    async getDirectoryConfig() {
        return {
            filters: [
                {
                    id: "genres",
                    title: "Genres",
                    type: daisuke_1.FilterType.EXCLUDABLE_MULTISELECT,
                    options: constants_1.GENRES,
                },
                {
                    id: "status",
                    title: "Status",
                    type: daisuke_1.FilterType.MULTISELECT,
                    options: constants_1.STATUSES,
                },
                {
                    id: "type",
                    title: "Type",
                    type: daisuke_1.FilterType.MULTISELECT,
                    options: constants_1.TYPES,
                },
                {
                    id: "demographic",
                    title: "Demographic",
                    type: daisuke_1.FilterType.MULTISELECT,
                    options: constants_1.DEMOGRAPHICS,
                },
            ],
            sort: {
                options: constants_1.SORTS,
                canChangeOrder: true,
                default: { id: "chapter_updated_at" },
            },
        };
    }
}
exports.Target = Target;
function mangaToHighlight(manga) {
    return {
        id: manga.hid,
        title: manga.title,
        cover: manga.poster?.large ?? "",
    };
}
function convertStatus(status) {
    switch (status) {
        case "releasing":
            return daisuke_1.PublicationStatus.ONGOING;
        case "finished":
            return daisuke_1.PublicationStatus.COMPLETED;
        case "on_hiatus":
            return daisuke_1.PublicationStatus.HIATUS;
        case "discontinued":
            return daisuke_1.PublicationStatus.CANCELLED;
        default:
            return daisuke_1.PublicationStatus.ONGOING;
    }
}
function chapterToChapter(ch, index) {
    const title = ch.name
        ? `Chapter ${ch.number}: ${ch.name}`
        : `Chapter ${ch.number}`;
    let providers;
    if (ch.group) {
        providers = [
            {
                id: ch.group.name,
                name: ch.group.name,
                links: [],
            },
        ];
    }
    else if (ch.is_official) {
        providers = [{ id: "official", name: "Official", links: [] }];
    }
    return {
        chapterId: ch.id.toString(),
        number: ch.number,
        title,
        index,
        date: parseRelativeDate(ch.created_at_formatted),
        language: "EN_US",
        ...(providers && { providers }),
    };
}
function parseRelativeDate(dateStr) {
    if (!dateStr)
        return new Date(0);
    const trimmed = dateStr
        .trim()
        .toLowerCase()
        .replace(/\s+ago$/, "");
    const match = trimmed.match(/^(\d+)\s*(s|m|h|d|w|mo|mos|y|yr|yrs|min|mins|sec|secs|hr|hrs|day|days|week|weeks|month|months|year|years)$/);
    if (!match)
        return new Date(0);
    const amount = parseInt(match[1], 10);
    const unit = match[2];
    const date = new Date();
    switch (unit) {
        case "s":
        case "sec":
        case "secs":
            date.setSeconds(date.getSeconds() - amount);
            break;
        case "m":
        case "min":
        case "mins":
            date.setMinutes(date.getMinutes() - amount);
            break;
        case "h":
        case "hr":
        case "hrs":
            date.setHours(date.getHours() - amount);
            break;
        case "d":
        case "day":
        case "days":
            date.setDate(date.getDate() - amount);
            break;
        case "w":
        case "week":
        case "weeks":
            date.setDate(date.getDate() - amount * 7);
            break;
        case "mo":
        case "mos":
        case "month":
        case "months":
            date.setMonth(date.getMonth() - amount);
            break;
        case "y":
        case "yr":
        case "yrs":
        case "year":
        case "years":
            date.setFullYear(date.getFullYear() - amount);
            break;
    }
    return date;
}
